// Content for generated service pages. One object = one page at /<slug>.
// Keep claims factual: no invented clients, numbers, reviews or timelines.
// After editing, run:  node scripts/build-pages.mjs

export const projects = {
  health: { name: "SR Health Care", type: "Healthcare app", platform: "Android · iOS", role: "App, backend, database, store launch", stack: "Flutter · REST API · SQL" },
  imoda: { name: "iModa", type: "Mobile product", platform: "Android · iOS", role: "App development, API integration, release", stack: "Flutter · Dart · REST API" },
  food: { name: "OneFoodDialer", type: "Food-tech platform", platform: "Mobile · web backend", role: "App, backend, payments, API gateway", stack: "Flutter · Laravel · Razorpay · Kong" },
  inventory: { name: "Inventory Management", type: "Business SaaS", platform: "Mobile · dashboard", role: "Full stack: app, API, database", stack: "Flutter · FastAPI · SQL" },
  arcade: { name: "Arcade Game", type: "Mobile game", platform: "Mobile", role: "Game design & development", stack: "Flutter · Dart" },
};

export const services = [
  {
    slug: "web-development",
    nav: "Web development",
    formValue: "Website / web app",
    title: "Website Development Services by a Freelance Web Developer | Atif",
    description: "Freelance website development: fast, mobile-first, SEO-ready business websites with Laravel, PHP or Next.js — hosted, secured and maintained.",
    eyebrow: "Website development",
    h1: "Website development that turns visitors into clients",
    intro: [
      "Your website is often the first thing a client checks before they call you. I build fast, mobile-first websites with a clean structure that Google can read and visitors can act on — contact forms, WhatsApp buttons, quote requests and bookings that actually reach you.",
      "As a freelance web developer I handle the whole job: design, development, content structure, hosting, domain, SSL and ongoing maintenance, so you have one person to talk to instead of three vendors.",
    ],
    offersTitle: "Websites I build",
    offers: [
      ["Business & service websites", "Clear pages for your services, work and contact details, built to load fast on mobile."],
      ["Custom websites", "Designs that don't come from a template, with custom sections, forms and integrations."],
      ["Landing pages", "Focused single pages for a product, campaign or launch, with one clear call to action."],
      ["Website redesign & migration", "Rebuild a slow or outdated site without losing the pages that already bring traffic."],
      ["Admin panel & CMS", "Edit your content, products or listings yourself through a simple admin area."],
      ["Maintenance & optimisation", "Updates, backups, security fixes and speed improvements after launch."],
    ],
    included: ["Mobile-first responsive design", "SEO-friendly structure, titles and meta tags", "Contact forms, WhatsApp and email CTAs", "Page speed and Core Web Vitals optimisation", "Hosting, domain and SSL setup", "Sitemap, robots.txt and Search Console setup"],
    stack: ["Laravel", "PHP", "Next.js", "Node.js", "JavaScript", "MySQL", "Hostinger", "AWS"],
    work: ["food", "inventory"],
    costFactors: ["Number of pages and unique page layouts", "Custom design vs adapting an existing design", "Admin panel or CMS requirements", "Integrations (payments, CRM, WhatsApp, booking)", "Content writing and migration from an old site"],
    faqs: [
      ["Can you build my website with an admin panel so I can edit it myself?", "Yes. I can add a simple admin area, built with Laravel for example, where you can update text, images, services or products without touching code."],
      ["Will my website be SEO-friendly?", "Yes. Every site gets a clean heading structure, unique titles and descriptions, fast loading, a sitemap, robots.txt and correct canonical URLs. Rankings also depend on content and competition, so I don't promise positions, but the technical foundation will be right."],
      ["Do you also host and maintain the website?", "Yes. I can set up hosting on Hostinger, cPanel or AWS, connect your domain and SSL, and maintain the site afterwards with updates, backups and fixes."],
      ["Can you redesign my existing website?", "Yes. I rebuild it on a faster stack and keep your important URLs (or redirect them properly) so you don't lose existing search traffic."],
    ],
    related: ["web-app-development", "ecommerce-development", "devops-server-management", "backend-development"],
  },
  {
    slug: "web-app-development",
    nav: "Web app development",
    formValue: "Website / web app",
    title: "Custom Web Application Development | Freelance Developer Atif",
    description: "Custom web application development: dashboards, portals, internal tools and SaaS apps with Laravel, FastAPI, Node.js or Next.js.",
    eyebrow: "Web application development",
    h1: "Custom web applications built around your workflow",
    intro: [
      "When spreadsheets, WhatsApp groups and off-the-shelf tools stop keeping up, a custom web application puts your process in one place: orders, inventory, bookings, reports, users and permissions, designed around how your team actually works.",
      "I build the full application myself: the interface, the backend API, the database and the deployment. The same backend can also power a mobile app later.",
    ],
    offersTitle: "Web apps I build",
    offers: [
      ["Admin dashboards", "Manage users, orders, content and reports from one secure panel."],
      ["Client & partner portals", "Give customers or vendors their own login to track orders, documents or requests."],
      ["Internal business tools", "Inventory, operations, CRM-style tools and approval workflows."],
      ["SaaS applications", "Multi-user apps with roles, subscriptions and billing."],
      ["Booking & ordering systems", "Online ordering, appointments and scheduling with payments."],
      ["Reporting & analytics", "Charts and exports built on your own data."],
    ],
    included: ["Requirement mapping and user roles", "Secure authentication and permissions", "REST API and database design", "Responsive UI for desktop and mobile", "Payment and third-party integrations", "Deployment, backups and documentation"],
    stack: ["Laravel", "PHP", "Python", "FastAPI", "Django", "Node.js", "Next.js", "PostgreSQL", "MySQL", "MongoDB", "Docker", "AWS"],
    work: ["inventory", "food"],
    costFactors: ["Number of user roles and screens", "Complexity of business rules and workflows", "Integrations (payments, APIs, email, WhatsApp)", "Reporting and data exports", "Hosting, scaling and security requirements"],
    faqs: [
      ["What's the difference between a website and a web application?", "A website mainly presents information. A web application lets users log in and do things: manage orders, track inventory, book slots or view reports. It needs a backend, a database and user permissions."],
      ["Can the same backend power a mobile app too?", "Yes. I design the API so a Flutter mobile app can use the same backend and database as the web app."],
      ["Do you build SaaS products?", "Yes. I build multi-user applications with roles, subscriptions and payment integration. We usually start with a focused first version and grow it from real user feedback."],
      ["Who owns the code?", "You do. After payment you get the full source code, database and deployment access."],
    ],
    related: ["backend-development", "web-development", "mobile-app-development", "payment-gateway-integration"],
  },
  {
    slug: "ecommerce-development",
    nav: "E-commerce development",
    formValue: "E-commerce website",
    title: "E-commerce Website Development — Custom Online Stores | Atif",
    description: "E-commerce website development: custom online stores and shopping apps with cart, checkout, Razorpay payments and an admin panel.",
    eyebrow: "E-commerce development",
    h1: "E-commerce websites and apps that are built to sell",
    intro: [
      "A store that is slow, confusing at checkout or hard to manage loses sales every day. I build custom e-commerce websites and mobile shopping apps with a fast catalogue, a simple cart and checkout, reliable payments and an admin panel your team can run without a developer.",
      "I've built online ordering with Razorpay payments behind an API gateway, so I understand the parts that break stores in production: payment callbacks, stock, order status and notifications.",
    ],
    offersTitle: "What I build for online stores",
    offers: [
      ["Custom online stores", "Catalogue, product pages, search and filters designed around your products."],
      ["Checkout & payments", "Cart, coupons, shipping rules and Razorpay (UPI, cards, net banking) with webhook-verified orders."],
      ["Order & inventory management", "Admin panel for orders, stock, customers, refunds and invoices."],
      ["Shopping apps", "Android and iOS apps with Flutter that share the same backend as your website."],
      ["Integrations", "Shipping, WhatsApp order updates, email and accounting or ERP tools via APIs."],
      ["Store performance & SEO", "Fast pages, clean product URLs and structured data for products."],
    ],
    included: ["Product catalogue and search", "Cart, checkout and payment gateway", "Order, stock and customer admin", "Email/WhatsApp order notifications", "Mobile-first design and SEO basics", "Hosting, SSL and backups"],
    stack: ["Laravel", "PHP", "Node.js", "Next.js", "Flutter", "Razorpay", "MySQL", "PostgreSQL", "Firebase", "AWS"],
    work: ["food"],
    costFactors: ["Number of products, variants and categories", "Custom design and features (subscriptions, multi-vendor, B2B pricing)", "Payment, shipping and ERP integrations", "Web store only, or web + mobile app", "Migration from an existing store"],
    faqs: [
      ["Which payment gateways can you integrate?", "I've integrated Razorpay in production, including webhook verification for payments. Other gateways with a documented API can be integrated the same way."],
      ["Can I manage products and orders myself?", "Yes. You get an admin panel to add products, manage stock, process orders and see customers, without touching code."],
      ["Can you build a mobile app for my store too?", "Yes. I build Flutter apps for Android and iOS that use the same backend, so products, prices and orders stay in sync."],
      ["Custom store or Shopify/WooCommerce?", "If a hosted platform covers your needs, I'll tell you. Custom development makes sense when you need your own business rules, integrations or a combined web + app experience."],
    ],
    related: ["payment-gateway-integration", "web-development", "mobile-app-development", "api-integration"],
  },
  {
    slug: "mobile-app-development",
    nav: "Mobile app development",
    formValue: "Mobile app (Android & iOS)",
    title: "Mobile App Development — Android & iOS | Freelance App Developer",
    description: "Freelance mobile app development for Android & iOS: Flutter apps with backend, payments and Play Store & App Store publishing.",
    eyebrow: "Mobile app development",
    h1: "Mobile app development for Android and iOS",
    intro: [
      "I build mobile apps for Android and iOS from one Flutter codebase, so you get both platforms without paying for two separate apps. You also get the part most app developers leave out: the backend, database, payments and the launch on Google Play and the App Store.",
      "I've shipped apps in healthcare, food-tech, business SaaS and gaming, and I stay involved after launch for updates and new features.",
    ],
    offersTitle: "Apps I build",
    offers: [
      ["Cross-platform apps", "One Flutter codebase for Android and iOS, with a native look and smooth performance."],
      ["Business & service apps", "Booking, ordering, healthcare, delivery and customer apps."],
      ["Apps with a backend", "APIs, database, admin panel and user accounts built together with the app."],
      ["Payments & notifications", "Razorpay in-app payments, push notifications and real-time updates."],
      ["Store publishing", "Signing, release builds, listings and review for Play Store and App Store."],
      ["Maintenance & new features", "OS updates, bug fixes and new features after launch."],
    ],
    included: ["UI from your design, or designed with you", "Android and iOS from one codebase", "Backend API, database and admin panel", "Push notifications and payments", "Play Store and App Store publishing", "Source code and documentation"],
    stack: ["Flutter", "Dart", "Java", "Firebase", "Laravel", "FastAPI", "Node.js", "Serverpod", "Razorpay", "AWS"],
    work: ["health", "imoda", "food", "inventory", "arcade"],
    costFactors: ["Number of screens and user roles", "Whether a backend and admin panel are needed", "Payments, maps, chat or other integrations", "Offline support and real-time features", "Design work and number of revisions"],
    faqs: [
      ["Do you build native or cross-platform apps?", "Mostly cross-platform with Flutter, which gives near-native performance on Android and iOS from one codebase. I use native Java for Android-specific modules when a project needs it."],
      ["Will you publish the app on the Play Store and App Store?", "Yes. I handle signing, release builds, store listings and review submission. You'll need your own developer accounts so the apps are published under your name."],
      ["Can you also build the backend and admin panel?", "Yes, that's one of my main strengths. I build the API, database and admin panel with Laravel, FastAPI, Node.js or Serverpod, and deploy it for you."],
      ["Can you take over an existing app?", "Yes. I start with a code review, fix what's urgent and then continue development."],
    ],
    related: ["flutter-development", "backend-development", "payment-gateway-integration", "devops-server-management"],
  },
  {
    slug: "flutter-development",
    nav: "Flutter development",
    formValue: "Mobile app (Android & iOS)",
    title: "Hire a Flutter Developer — Flutter App Development | Atif",
    description: "Hire a freelance Flutter developer for Android & iOS apps — clean Dart code, Firebase or API integration and a Laravel, FastAPI or Serverpod backend.",
    eyebrow: "Flutter development",
    h1: "Hire a Flutter developer who also builds the backend",
    intro: [
      "Flutter is my main tool for mobile apps. Every product in my portfolio (healthcare, food ordering, inventory and a game) is built with Flutter and Dart. When you hire me you get a Flutter developer who also understands the other side of the app: APIs, databases, payments and deployment.",
      "That matters, because most app problems in production aren't in the UI. They're in the connection between the app and the backend.",
    ],
    offersTitle: "Flutter work I take on",
    offers: [
      ["New Flutter apps", "From first screen to store release, for Android and iOS."],
      ["Flutter + backend", "Flutter apps paired with Laravel, FastAPI, Node.js or Serverpod (Dart on the server)."],
      ["Firebase apps", "Auth, Firestore, push notifications and analytics with Firebase."],
      ["Existing app takeover", "Code review, refactoring, dependency upgrades and bug fixes."],
      ["Performance & architecture", "Clean state management, modular code and faster builds."],
      ["Flutter web & dashboards", "Admin panels and companion web apps that reuse your Dart code."],
    ],
    included: ["Clean, documented Dart code", "State management set up for growth", "REST API or Firebase integration", "Push notifications, payments, deep links", "Play Store and App Store releases", "Handover and knowledge transfer"],
    stack: ["Flutter", "Dart", "Serverpod", "Firebase", "REST APIs", "Laravel", "FastAPI", "Node.js", "Razorpay"],
    work: ["health", "imoda", "food", "inventory", "arcade"],
    costFactors: ["App size and number of screens", "Backend: new, existing, or Firebase", "Integrations and device features", "Taking over an existing codebase vs starting fresh", "Ongoing support after launch"],
    faqs: [
      ["Why Flutter instead of separate native apps?", "One codebase for Android and iOS means lower cost, faster releases and one set of bugs to fix. For most business apps the performance is indistinguishable from native."],
      ["Can you work with my existing Flutter code?", "Yes. I'll review the code, flag risks and continue development, or refactor the parts that are slowing you down."],
      ["What is Serverpod?", "Serverpod is a backend framework written in Dart. It lets the app and server share models and code, which is a good fit for Flutter-first teams. I also build backends with Laravel, FastAPI and Node.js."],
      ["Can I hire you part-time or for a fixed scope?", "Both work. Fixed scope suits a defined app or feature. Ongoing monthly support suits continuous development."],
    ],
    related: ["mobile-app-development", "backend-development", "api-integration", "payment-gateway-integration"],
  },
  {
    slug: "backend-development",
    nav: "Backend & API development",
    formValue: "Backend / API / Database",
    title: "Backend & API Development — Hire a Backend Developer | Atif",
    description: "Freelance backend & API development: secure REST APIs and databases with Laravel, PHP, Python (FastAPI, Django) and Node.js.",
    eyebrow: "Backend & API development",
    h1: "Backend and API development for web and mobile apps",
    intro: [
      "The backend is where your business rules, data and money live. I design and build REST APIs, databases and server logic that power web apps and mobile apps reliably: authentication, roles, payments, notifications, reports and integrations.",
      "I've built backends with Laravel, FastAPI and Serverpod, put them behind the Kong API gateway, and deployed them to production servers.",
    ],
    offersTitle: "Backend work I do",
    offers: [
      ["REST API development", "Documented, versioned APIs for your web and mobile apps."],
      ["Database design & development", "PostgreSQL, MySQL or MongoDB schemas, migrations, indexing and query tuning."],
      ["Authentication & roles", "Secure login, tokens, permissions and audit trails."],
      ["API gateway & security", "Rate limiting, routing and auth with Kong."],
      ["Background jobs & real-time", "Queues, scheduled tasks, webhooks and live updates."],
      ["Backend rescue", "Fix slow, unstable or undocumented backends and make them maintainable."],
    ],
    included: ["API design and documentation", "Database schema and migrations", "Auth, roles and validation", "Payment and third-party integrations", "Logging, error handling and backups", "Deployment and handover"],
    stack: ["Laravel", "PHP", "Python", "FastAPI", "Django", "Node.js", "Serverpod", "PostgreSQL", "MySQL", "MongoDB", "Kong", "Docker", "AWS"],
    work: ["food", "inventory", "health"],
    costFactors: ["Number of endpoints and business rules", "Data model complexity and migrations", "Integrations (payments, messaging, third-party APIs)", "Performance, security and compliance needs", "Hosting and DevOps setup"],
    faqs: [
      ["Which backend framework should I use?", "It depends on your team and product. Laravel is great for business apps and admin panels, FastAPI for Python-heavy or AI features, Node.js for real-time and JavaScript teams, and Serverpod for Flutter-first products. I'll recommend one based on your needs, not habit."],
      ["Can you build just the API for my existing app?", "Yes. I can build or extend an API for an existing web or mobile frontend and document it so your team can use it."],
      ["Do you design the database too?", "Yes. Database design, migrations, indexing and backups are part of every backend I build."],
      ["Can you improve a slow backend?", "Yes. I profile slow endpoints and queries, add indexes and caching, and fix the root causes."],
    ],
    related: ["api-integration", "web-app-development", "devops-server-management", "flutter-development"],
  },
  {
    slug: "api-integration",
    nav: "API integration",
    formValue: "Payment gateway / API integration",
    title: "API Integration Services — Third-Party & WhatsApp APIs | Atif",
    description: "API integration services: connect your website, app or CRM to third-party APIs, WhatsApp, payment gateways and webhooks — reliably.",
    eyebrow: "API integration",
    h1: "API integration that connects your tools",
    intro: [
      "Most businesses run on several tools that don't talk to each other. I connect them through APIs so data moves automatically: orders into your accounting tool, leads into your CRM, updates to customers on WhatsApp, and payments confirmed by webhook instead of by hand.",
      "Good integrations aren't just 'call the API'. They handle retries, timeouts, duplicate events and logging, so nothing silently breaks at 2 a.m.",
    ],
    offersTitle: "Integrations I build",
    offers: [
      ["Third-party API integration", "Connect your app or website to external services and SaaS tools."],
      ["WhatsApp API integration", "Order updates, notifications and customer messages through WhatsApp APIs."],
      ["Payment integrations", "Razorpay payments, refunds and subscriptions with webhook verification."],
      ["Webhooks & event flows", "React to events from other systems in real time."],
      ["Internal system sync", "Keep CRM, ERP, inventory and databases in sync."],
      ["API gateway setup", "Secure and monitor your APIs with Kong."],
    ],
    included: ["Integration design and data mapping", "Secure credential handling", "Retries, idempotency and error handling", "Logging and alerting", "Testing against sandbox environments", "Documentation for your team"],
    stack: ["REST APIs", "Webhooks", "Razorpay", "WhatsApp APIs", "Kong", "Laravel", "FastAPI", "Node.js", "Python"],
    work: ["food"],
    costFactors: ["Number of systems to connect", "Quality of each provider's API and documentation", "One-way vs two-way sync", "Volume and real-time requirements", "Monitoring and support needs"],
    faqs: [
      ["Can you integrate WhatsApp with my website or app?", "Yes. I can send order updates, alerts and notifications through WhatsApp APIs, or connect incoming messages to your system."],
      ["What if the third-party API is poorly documented?", "I test against their sandbox, log real responses and build defensive handling around edge cases. I'll also tell you early if an integration is risky."],
      ["Can you connect my app to my CRM or ERP?", "If the system has an API (most do), yes. I map your data, build the sync and add monitoring."],
    ],
    related: ["payment-gateway-integration", "backend-development", "business-automation", "ai-development"],
  },
  {
    slug: "payment-gateway-integration",
    nav: "Payment gateway integration",
    formValue: "Payment gateway / API integration",
    title: "Payment Gateway Integration — Razorpay for Web & Apps | Atif",
    description: "Payment gateway integration for websites and Flutter apps: Razorpay checkout, UPI, subscriptions, refunds and webhook verification.",
    eyebrow: "Payment gateway integration",
    h1: "Payment gateway integration for websites and apps",
    intro: [
      "Payments have to be correct every time. I integrate payment gateways into websites, web apps and Flutter mobile apps, including the server-side part many integrations get wrong: verifying payments with signatures and webhooks before an order is marked as paid.",
      "I've integrated Razorpay in a production food-ordering platform, from app checkout to backend order updates.",
    ],
    offersTitle: "Payment work I do",
    offers: [
      ["Razorpay checkout", "UPI, cards, net banking and wallets in your website or app."],
      ["Server-side verification", "Signature and webhook verification, so orders can't be faked."],
      ["Subscriptions & recurring billing", "Plans, renewals and failed-payment handling for SaaS and memberships."],
      ["Refunds & reconciliation", "Refund flows and matching payments to orders in your admin panel."],
      ["Flutter in-app payments", "Native payment flow in Android and iOS apps."],
      ["Fixing broken integrations", "Missing webhooks, duplicate orders and payment-status mismatches."],
    ],
    included: ["Checkout on web and/or app", "Backend order and payment records", "Webhook handling and signature checks", "Refunds and status updates", "Test mode → live mode go-live checklist", "Documentation for your team"],
    stack: ["Razorpay", "Webhooks", "Laravel", "PHP", "FastAPI", "Node.js", "Flutter", "MySQL", "PostgreSQL"],
    work: ["food"],
    costFactors: ["One-time payments vs subscriptions", "Web, app, or both", "Existing backend or new", "Refund and reconciliation needs", "Number of payment flows (orders, wallets, payouts)"],
    faqs: [
      ["Do you integrate Razorpay in Flutter apps?", "Yes. I integrate Razorpay checkout in Flutter apps and verify every payment on the backend before confirming the order."],
      ["Why do I need webhooks if checkout already works?", "Because users close apps, networks drop and callbacks fail. Webhooks let your server confirm the payment independently, which prevents unpaid orders and missing ones."],
      ["Can you fix my existing payment integration?", "Yes. I'll audit the flow, fix verification and status handling, and add logging so issues are traceable."],
    ],
    related: ["ecommerce-development", "api-integration", "mobile-app-development", "backend-development"],
  },
  {
    slug: "ai-development",
    nav: "AI development",
    formValue: "AI / LLM integration",
    title: "AI Development & AI Integration Services | Freelance Developer",
    description: "AI development & integration: LLM chatbots, smart search (RAG), document Q&A and AI automation for your website, app or internal tools.",
    eyebrow: "AI development & integration",
    h1: "AI development and integration for real business use",
    intro: [
      "AI is useful when it's connected to your data and your workflow, not as a demo. I integrate large language models into existing websites, apps and internal tools: assistants that answer from your documents, search that understands meaning, and automations that read, classify and draft for your team.",
      "I work with hosted AI APIs and private local models, and build the backend around them with Python (FastAPI) and vector databases.",
    ],
    offersTitle: "AI features I build",
    offers: [
      ["AI chatbots & assistants", "Answer customer or staff questions using your own content."],
      ["Smart search (RAG)", "Semantic search over documents, products or tickets with a vector database."],
      ["Document Q&A & extraction", "Pull structured data from PDFs, forms and emails."],
      ["AI automation", "Classify, summarise, draft and route work automatically."],
      ["AI in existing apps", "Add AI features to your current website, Flutter app or backend."],
      ["Private & local models", "Run models on your own infrastructure when data can't leave it."],
    ],
    included: ["Use-case scoping and feasibility check", "Data preparation and embeddings", "LLM integration with guardrails", "Backend API (FastAPI / Node.js)", "Evaluation on real examples", "Cost and usage monitoring"],
    stack: ["Python", "FastAPI", "LLM APIs", "Vector databases", "Local models", "Node.js", "PostgreSQL", "Docker"],
    work: [],
    costFactors: ["Use case and required accuracy", "Amount and format of your data", "Hosted API vs local model", "Integration into existing systems", "Ongoing model usage costs"],
    faqs: [
      ["Can you add AI to my existing app?", "Yes. I usually add AI as a backend service (for example with FastAPI) that your current web or mobile app calls, so your app doesn't need a rewrite."],
      ["Will my data be private?", "We choose the setup based on your data. Hosted APIs with appropriate settings, or local models running on your own server when data must not leave it."],
      ["How do you make sure the AI gives correct answers?", "By grounding answers in your own documents (retrieval), adding guardrails, and testing on real questions from your business before launch. AI can still make mistakes, so we design the workflow with a human check where it matters."],
    ],
    related: ["business-automation", "backend-development", "api-integration", "web-app-development"],
  },
  {
    slug: "business-automation",
    nav: "Business automation",
    formValue: "Automation / testing",
    title: "Business & Workflow Automation Services | Freelance Developer",
    description: "Business & workflow automation with Python, Playwright and APIs: automate data entry, reports, browser tasks and notifications.",
    eyebrow: "Business automation",
    h1: "Business and workflow automation that saves hours",
    intro: [
      "If someone on your team copies data between tools, downloads the same report every morning or checks websites by hand, that work can usually be automated. I build reliable automations with Python, Playwright and APIs that run on a schedule, alert you when something changes and log everything they do.",
      "Where it helps, I add AI to read, classify or summarise. Where it doesn't, a simple script is often the better answer.",
    ],
    offersTitle: "What I automate",
    offers: [
      ["Repetitive data entry", "Move data between spreadsheets, CRMs, portals and databases."],
      ["Browser automation", "Playwright bots for portals that have no API."],
      ["Scheduled reports", "Daily or weekly reports generated and sent automatically."],
      ["Workflow automation", "Approvals, notifications and hand-offs between tools and people."],
      ["Automated testing", "End-to-end tests that catch broken releases before users do."],
      ["Monitoring & alerts", "Get notified on WhatsApp or email when something needs attention."],
    ],
    included: ["Process mapping with your team", "Automation scripts or services", "Scheduling and retries", "Logs and failure alerts", "Documentation and handover", "Optional hosting and monitoring"],
    stack: ["Python", "Playwright", "REST APIs", "Webhooks", "FastAPI", "Node.js", "Docker", "AWS", "AI APIs"],
    work: [],
    costFactors: ["Number of steps and systems involved", "API available vs browser automation needed", "Run frequency and data volume", "Error handling and alerting needs", "Hosting and ongoing maintenance"],
    faqs: [
      ["What kinds of tasks can be automated?", "Anything repetitive and rule-based: data entry, report generation, moving data between tools, checking portals, sending reminders and testing websites."],
      ["What if the website or portal has no API?", "I use Playwright to automate the browser the way a person would, with safeguards for slow pages and layout changes."],
      ["Where do the automations run?", "On a small cloud server, your own server, or scheduled on existing infrastructure. I set up logging and alerts either way."],
    ],
    related: ["ai-development", "api-integration", "devops-server-management", "backend-development"],
  },
  {
    slug: "devops-server-management",
    nav: "DevOps & server management",
    formValue: "Cloud / AWS / server management",
    title: "DevOps, AWS & Server Management Services | Freelance Developer",
    description: "DevOps & server management: deploy and maintain apps on AWS, Docker, Hostinger and cPanel with SSL, backups and monitoring.",
    eyebrow: "DevOps & server management",
    h1: "DevOps, cloud deployment and server management",
    intro: [
      "Code only helps your business when it's running reliably. I deploy and manage websites, backend APIs and databases on AWS, with S3 storage and Docker, or on Hostinger (hPanel) and cPanel hosting, with domains, SSL, backups and monitoring set up properly.",
      "I also take over servers that 'just work' until they don't: undocumented setups, expiring certificates, full disks and missing backups.",
    ],
    offersTitle: "What I set up and manage",
    offers: [
      ["Cloud deployment on AWS", "Servers, S3 storage, environments and secure access."],
      ["Docker & deployments", "Containerised apps and repeatable, low-risk releases."],
      ["Shared & VPS hosting", "Hostinger (hPanel) and cPanel setup, migration and upkeep."],
      ["Domains, SSL & email", "DNS, HTTPS certificates and business email configuration."],
      ["Backups & monitoring", "Automated backups, uptime checks and alerts."],
      ["Performance & security", "Faster servers, fewer attack surfaces, safer updates."],
    ],
    included: ["Server or cloud setup", "Deployment of web app / API / database", "Domain, DNS and SSL", "Backups and restore test", "Monitoring and alerts", "Access and runbook documentation"],
    stack: ["AWS", "S3", "Docker", "Hostinger", "hPanel", "cPanel", "PostgreSQL", "MySQL", "MongoDB"],
    work: ["food", "health"],
    costFactors: ["Number of apps, environments and databases", "AWS vs shared/VPS hosting", "Migration from an existing server", "Monitoring and on-call expectations", "Monthly maintenance vs one-time setup"],
    faqs: [
      ["Can you move my website or app to AWS?", "Yes. I plan the migration, move the app and database, switch DNS with minimal downtime and keep the old server as a fallback until everything is verified."],
      ["Do you offer monthly server maintenance?", "Yes. Updates, backups, monitoring, SSL renewals and fixes on a monthly basis."],
      ["Should I use AWS or regular hosting?", "For a business website, good shared or VPS hosting is often enough and cheaper. AWS makes sense for APIs, apps with growing traffic and more control. I'll recommend based on your needs and budget."],
    ],
    related: ["backend-development", "web-development", "business-automation", "web-app-development"],
  },
];
